name: Code Generation

on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  codegen:
    name: Regenerate Ariadne Codegen
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Git Config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "mickey.mouse@playerdata.com"
          git config --global push.autoSetupRemote true

      - name: Generate Branch Name
        id: branch-name
        run: echo "branch-name=codegen-$(openssl rand -hex 4)" >> "$GITHUB_OUTPUT"

      - run: git checkout -b ${{ steps.branch-name.outputs.branch-name }}

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v6.6.1
        with:
          enable-cache: true
          cache-suffix: '-venv-codegen'
          activate-environment: true

      - name: Install Dependencies
        run: uv sync --group codegen --locked

      - name: Fetch the Schema
        run: uv run --no-sync scripts/fetch_schema.py

      - name: Code Generation
        run: uv run --no-sync ariadne-codegen

      - name: Fix Imports
        run: uv run --no-sync scripts/fixup.py

      - name: Generate GitHub App Token
        id: app_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: 73365
          private-key: ${{ secrets.BEAVERBOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Create PR
        env:
          GH_TOKEN: ${{ steps.app_token.outputs.token }}
        run: |
          git add .
          git commit -m "chore: update graphql schema"
          git fetch origin
          git rebase origin/main -X theirs
          git push --force
          gh pr create \
            --title "Code Generation" \
            --body "Automagically generated schema updates." \
            --base main \
            --head ${{ steps.branch-name.outputs.branch-name }}
        
      # - name: Enable Automerge
      #   if: steps.create-pr.outputs.pull-request-number
      #   run: gh pr merge ${{ steps.create-pr.outputs.pull-request-number }} --auto --squash
      #   env:
      #     GH_TOKEN: ${{ github.token }}
