name: Publish Python

on:
  workflow_call:
    inputs:
      new_release_published:
        description: 'Whether a new release has been published'
        required: true
        type: string
      new_release_version:
        description: 'The latest release version'
        required: true
        type: string

jobs:
  publish:
    name: Publish Python Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    environment:
      name: pypi

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v7.2.1
        with:
          enable-cache: true
          cache-suffix: '-publish'
          activate-environment: true

      - name: Apply Semantic Version
        if: ${{ inputs.new_release_published == 'true' }}
        run: uv version ${{ inputs.new_release_version }}

      - name: Build
        if: ${{ inputs.new_release_published == 'true' }}
        run: uv build

      - name: Publish
        if: ${{ inputs.new_release_published == 'true' }}
        run: uv publish

